/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Graficos.Grafico;
import Graficos.datoGrafico;
import aplicacion.Administrador;
import aplicacion.Chofer;
import aplicacion.Licencia;
import aplicacion.Secretaria;
import aplicacion.Vehiculo;
import aplicacion.main;
import java.awt.Image;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author SSDesth
 */
public class frmAdministrados extends javax.swing.JFrame {
    
    private Administrador usuario;
    private List<Licencia> licenciasChofer = new ArrayList();

    
    /**
     * Creates new form frmAdministrados
     */
    public frmAdministrados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpRegisChofer = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblCantLicencias = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtfChoferNombre = new javax.swing.JTextField();
        jtfChoferTelefono = new javax.swing.JTextField();
        jtfChoferCorreo = new javax.swing.JTextField();
        jtfChoferCedula = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtfLicenciaTipo = new javax.swing.JTextField();
        jtfLicenciaFechaExpiracion = new javax.swing.JTextField();
        jtfLicenciaFechaEmicion = new javax.swing.JTextField();
        jtfLicenciaNombre = new javax.swing.JTextField();
        jcbChoferLicencias = new javax.swing.JComboBox<>();
        btnAgregarLicencia = new javax.swing.JButton();
        btnChoferQuitarLicencia = new javax.swing.JButton();
        btnChoferAgregar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnAtras5 = new javax.swing.JButton();
        lblFondo7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfVehiculoPlaca = new javax.swing.JTextField();
        jtfVehiculoAnioFabricacion = new javax.swing.JTextField();
        jtfVehiculoColor = new javax.swing.JTextField();
        jtfVehiculoMarca = new javax.swing.JTextField();
        jtfVehiculoCapacidad = new javax.swing.JTextField();
        jtfVehiculoKilometraje = new javax.swing.JTextField();
        jtfVehiculoVIN = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfVehiculoSede = new javax.swing.JTextField();
        btnAgregarVehiculo = new javax.swing.JButton();
        btnAtras4 = new javax.swing.JButton();
        lblFondo2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaListarViajes = new javax.swing.JTextArea();
        btnListarViajes = new javax.swing.JButton();
        btnAtras3 = new javax.swing.JButton();
        lblFondo3 = new javax.swing.JLabel();
        lblFondo1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnAtras2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jtfAprobarID = new javax.swing.JTextField();
        lblVehiculo = new javax.swing.JLabel();
        jcbAprobarVehiculo = new javax.swing.JComboBox<>();
        lblVehiculo1 = new javax.swing.JLabel();
        jcbAprobarChofer = new javax.swing.JComboBox<>();
        btnAprobarViaje = new javax.swing.JButton();
        lblFondo4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnAtras1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jtfSectretariaNombre = new javax.swing.JTextField();
        jtfSectretariaCorreo = new javax.swing.JTextField();
        jtfSectretariaTelefono = new javax.swing.JTextField();
        jtfSectretariaDepartamento = new javax.swing.JTextField();
        btnRegistrarSecretaria = new javax.swing.JButton();
        lblFondo5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        btnViajesPorEscuelas = new javax.swing.JButton();
        lblFondo6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpRegisChofer.setBackground(new java.awt.Color(0, 0, 255));
        jpRegisChofer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre:");
        jpRegisChofer.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 33, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Telefono:");
        jpRegisChofer.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 75, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Correo Electronico:");
        jpRegisChofer.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 118, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cedula:");
        jpRegisChofer.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 156, -1, -1));

        lblCantLicencias.setForeground(new java.awt.Color(255, 255, 255));
        lblCantLicencias.setText("Cant Licencias:");
        jpRegisChofer.add(lblCantLicencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 194, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Agregar Licencia:");
        jpRegisChofer.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 22, 281, 32));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Licencias");
        jpRegisChofer.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 233, -1, -1));
        jpRegisChofer.add(jtfChoferNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 30, 200, -1));
        jpRegisChofer.add(jtfChoferTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 72, 200, -1));
        jpRegisChofer.add(jtfChoferCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 115, 200, -1));
        jpRegisChofer.add(jtfChoferCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 153, 200, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Numero:");
        jpRegisChofer.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 75, -1, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Fecha de Emicio:");
        jpRegisChofer.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 118, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Fecha Expiracion:");
        jpRegisChofer.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 156, -1, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Tipo:");
        jpRegisChofer.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 194, -1, -1));

        jtfLicenciaTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfLicenciaTipoActionPerformed(evt);
            }
        });
        jpRegisChofer.add(jtfLicenciaTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 191, 169, -1));
        jpRegisChofer.add(jtfLicenciaFechaExpiracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 153, 169, -1));
        jpRegisChofer.add(jtfLicenciaFechaEmicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 115, 169, -1));
        jpRegisChofer.add(jtfLicenciaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 72, 169, -1));

        jcbChoferLicencias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpRegisChofer.add(jcbChoferLicencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 270, 116, -1));

        btnAgregarLicencia.setText("Agregar Licencia");
        btnAgregarLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLicenciaActionPerformed(evt);
            }
        });
        jpRegisChofer.add(btnAgregarLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 229, 169, -1));

        btnChoferQuitarLicencia.setText("Quitar Licencia");
        btnChoferQuitarLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoferQuitarLicenciaActionPerformed(evt);
            }
        });
        jpRegisChofer.add(btnChoferQuitarLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 317, 116, -1));

        btnChoferAgregar.setText("Agregar Chofer");
        btnChoferAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoferAgregarActionPerformed(evt);
            }
        });
        jpRegisChofer.add(btnChoferAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 317, 201, -1));

        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Formato: dd-MM-aaaa");
        jpRegisChofer.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 95, -1, -1));

        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Formato: dd-MM-aaaa");
        jpRegisChofer.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 138, -1, -1));

        btnAtras5.setText("Atras");
        btnAtras5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras5ActionPerformed(evt);
            }
        });
        jpRegisChofer.add(btnAtras5, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 331, -1, -1));
        jpRegisChofer.add(lblFondo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 890, 370));

        jTabbedPane1.addTab("Registrar Chofer", jpRegisChofer);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Placa:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Año Fabricacion:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Color:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Marca:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 128, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Capacidad:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kilometraje:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 204, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("VIN:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 242, -1, -1));
        jPanel1.add(jtfVehiculoPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 11, 146, -1));
        jPanel1.add(jtfVehiculoAnioFabricacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 49, 147, -1));
        jPanel1.add(jtfVehiculoColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 87, 147, -1));

        jtfVehiculoMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfVehiculoMarcaActionPerformed(evt);
            }
        });
        jPanel1.add(jtfVehiculoMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 125, 147, -1));
        jPanel1.add(jtfVehiculoCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 163, 147, -1));
        jPanel1.add(jtfVehiculoKilometraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 201, 147, -1));
        jPanel1.add(jtfVehiculoVIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 239, 147, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sede Pertenecia:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        jPanel1.add(jtfVehiculoSede, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 277, 147, -1));

        btnAgregarVehiculo.setText("Agregar Vehiculo");
        btnAgregarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarVehiculoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 315, 147, -1));

        btnAtras4.setText("Atras");
        btnAtras4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras4, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 331, -1, -1));
        jPanel1.add(lblFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 840, 370));

        jTabbedPane1.addTab("Registrar Vehiculo", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtaListarViajes.setColumns(20);
        jtaListarViajes.setRows(5);
        jScrollPane1.setViewportView(jtaListarViajes);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 41, 281, 283));

        btnListarViajes.setText("Listar Viajes");
        btnListarViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarViajesActionPerformed(evt);
            }
        });
        jPanel2.add(btnListarViajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 41, 168, -1));

        btnAtras3.setText("Atras");
        btnAtras3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAtras3, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 331, -1, -1));
        jPanel2.add(lblFondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 840, 370));
        jPanel2.add(lblFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -16, 750, 380));

        jTabbedPane1.addTab("Listar Viajes", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 0, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtras2.setText("Atras");
        btnAtras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAtras2, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 331, -1, -1));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("IVA-");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, 49, -1));
        jPanel3.add(jtfAprobarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 49, 150, -1));

        lblVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblVehiculo.setText("Vehiculo:");
        jPanel3.add(lblVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 49, -1));

        jcbAprobarVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jcbAprobarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 87, 150, -1));

        lblVehiculo1.setForeground(new java.awt.Color(255, 255, 255));
        lblVehiculo1.setText("Chofer");
        jPanel3.add(lblVehiculo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 128, 49, -1));

        jcbAprobarChofer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jcbAprobarChofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 125, 150, -1));

        btnAprobarViaje.setText("Aprobar Viaje");
        btnAprobarViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprobarViajeActionPerformed(evt);
            }
        });
        jPanel3.add(btnAprobarViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 179, 150, -1));
        jPanel3.add(lblFondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 880, 370));

        jTabbedPane1.addTab("Aprobar Solicitud", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 0, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtras1.setText("Atras");
        btnAtras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnAtras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 331, -1, -1));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Nombre:");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 37, -1, -1));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Correo Electronico:");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, -1, -1));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Telefono:");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 113, -1, -1));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Departamento");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 151, -1, -1));
        jPanel4.add(jtfSectretariaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 34, 180, -1));
        jPanel4.add(jtfSectretariaCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 72, 180, -1));
        jPanel4.add(jtfSectretariaTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 110, 180, -1));
        jPanel4.add(jtfSectretariaDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 148, 180, -1));

        btnRegistrarSecretaria.setText("Registrar Secretaria");
        btnRegistrarSecretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarSecretariaActionPerformed(evt);
            }
        });
        jPanel4.add(btnRegistrarSecretaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 186, 180, -1));
        jPanel4.add(lblFondo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 900, 370));

        jTabbedPane1.addTab("Registrar Secretaria", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 0, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel5.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 331, -1, -1));

        btnViajesPorEscuelas.setText("Viajes Por Escuelas");
        btnViajesPorEscuelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViajesPorEscuelasActionPerformed(evt);
            }
        });
        jPanel5.add(btnViajesPorEscuelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 280, -1));
        jPanel5.add(lblFondo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 840, 370));

        jTabbedPane1.addTab("Consultar Datos", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfVehiculoMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfVehiculoMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfVehiculoMarcaActionPerformed

    private void btnAgregarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarVehiculoActionPerformed
        if (ValidarVehiculo()) {
            try {
                Vehiculo nuevoVehiculo = new Vehiculo();
                nuevoVehiculo.setPlaca(Integer.parseInt(jtfVehiculoPlaca.getText()));
                nuevoVehiculo.setAnioFabricación(Integer.parseInt(jtfVehiculoAnioFabricacion.getText()));
                nuevoVehiculo.setColor(jtfVehiculoColor.getText());
                nuevoVehiculo.setMarca(jtfVehiculoMarca.getText());
                nuevoVehiculo.setKilometraje(Double.parseDouble(jtfVehiculoKilometraje.getText()));
                nuevoVehiculo.setNúmeroVin(Integer.parseInt(jtfVehiculoVIN.getText()));
                nuevoVehiculo.setSedePertenenciaVehículo(jtfVehiculoSede.getText());
                
                if (usuario.RegistrarVehiculoNuevo(nuevoVehiculo)) {
                    JOptionPane.showMessageDialog(null, "El Vehiculo fue agregado\n"
                            + "exitosamente",
                            "Mensaje", 1);
                    LimpiarVehiculo();
                    CargadorAprobar();
                } else {
                    JOptionPane.showMessageDialog(null, "El Vehiculo no pudo\n"
                            + "Ser agregado",
                            "Alerta", 0);
                }
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null, "Placa/Año/Kilometraje/VIN\n"
                        + "solo pueden ser numeros",
                        "Alerta", 2);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Falta Algun dato por rellenar",
                    "Alerta", 2);
        }
        

    }//GEN-LAST:event_btnAgregarVehiculoActionPerformed

    private void jtfLicenciaTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfLicenciaTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfLicenciaTipoActionPerformed

    private void btnAgregarLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLicenciaActionPerformed
        if (ValidarLicencia()) {
            SimpleDateFormat traductor = new SimpleDateFormat("dd-MM-yyyy");
            Date fechatemp;
            try {
                Licencia nuevaLicencia = new Licencia();
                nuevaLicencia.setNumero(Integer.parseInt(jtfLicenciaNombre.getText()));
                
                fechatemp = traductor.parse(jtfLicenciaFechaEmicion.getText());
                nuevaLicencia.setFechaEmision(jtfLicenciaFechaEmicion.getText());
                
                fechatemp = traductor.parse(jtfLicenciaFechaExpiracion.getText());
                nuevaLicencia.setFechaExpiracion(jtfLicenciaFechaExpiracion.getText());
                
                nuevaLicencia.setTipo(jtfLicenciaTipo.getText());
                
                licenciasChofer.add(nuevaLicencia);
                CargadorComboChofer();
                LimpiarLicencia();
                CargadorAprobar();
                
            } catch (ParseException pe) {
                JOptionPane.showMessageDialog(null, "Algun dato no tirnr \n"
                        + "el formato deseado",
                        "Alerta", 2);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Falta Algun dato de la licencia",
                    "Alerta", 2);
        }
        

    }//GEN-LAST:event_btnAgregarLicenciaActionPerformed

    private void btnChoferQuitarLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoferQuitarLicenciaActionPerformed
        if (licenciasChofer.size()>0) {
            licenciasChofer.remove(jcbChoferLicencias.getSelectedIndex());
            CargadorComboChofer();
        }
        
    }//GEN-LAST:event_btnChoferQuitarLicenciaActionPerformed

    private void btnChoferAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoferAgregarActionPerformed
        
        if (ValidarChofer()) {
            try {
                Chofer nuevoChofer = new Chofer();
                nuevoChofer.setNombreCompleto(jtfChoferNombre.getText());
                nuevoChofer.setCedula(Integer.parseInt(jtfChoferCedula.getText()));
                nuevoChofer.setTelefono(Integer.parseInt(jtfChoferTelefono.getText()));
                nuevoChofer.setCorreo(jtfChoferCorreo.getText());
                nuevoChofer.setLicencias(licenciasChofer);
                
                if(usuario.RegistrarChoferNuevo(nuevoChofer)){
                    JOptionPane.showMessageDialog(null, "Chofer agregado Exitosamente",
                        "mensaje", 1);
                    LimpiarChofer();
                }
                else{
                    JOptionPane.showMessageDialog(null, "No se pudo Agregar el Chofer",
                        "Alerta", 0);
                }
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null, "Cedula y Telefono\n"
                        + "tiene que ser solo numeros",
                        "Alerta", 2);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Falta Algun dato del chofer",
                    "Alerta", 2);
        }
    }//GEN-LAST:event_btnChoferAgregarActionPerformed

    private void btnListarViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarViajesActionPerformed
        jtaListarViajes.setText(usuario.ListarViajesAdministrador());
    }//GEN-LAST:event_btnListarViajesActionPerformed

    private void btnAtras5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras5ActionPerformed
        main.miControlador.CargarVentanaloggin();
        this.dispose();
    }//GEN-LAST:event_btnAtras5ActionPerformed

    private void btnAtras4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras4ActionPerformed
       main.miControlador.CargarVentanaloggin();
        this.dispose();
    }//GEN-LAST:event_btnAtras4ActionPerformed

    private void btnAtras3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras3ActionPerformed
       main.miControlador.CargarVentanaloggin();
        this.dispose();
    }//GEN-LAST:event_btnAtras3ActionPerformed

    private void btnAtras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras2ActionPerformed
       main.miControlador.CargarVentanaloggin();
        this.dispose();
    }//GEN-LAST:event_btnAtras2ActionPerformed

    private void btnAtras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras1ActionPerformed
       main.miControlador.CargarVentanaloggin();
        this.dispose();
    }//GEN-LAST:event_btnAtras1ActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        main.miControlador.CargarVentanaloggin();
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAprobarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprobarViajeActionPerformed
        if(jtfAprobarID.getText().equals("")){
             JOptionPane.showMessageDialog(null,"No ingrego el IVA", "Alerta", 2);
            
        }else{
           Chofer entradaChofer = main.miControlador.getMiTec().getChoferes().
                    get(jcbAprobarChofer.getSelectedIndex());
            Vehiculo entradaVehiculo = main.miControlador.getMiTec().getVehiculos().
                    get(jcbAprobarChofer.getSelectedIndex());
            
            String ID="IVA-"+jtfAprobarID.getText();
            
            if(usuario.AprobarSolicitudAdministrador(entradaChofer, entradaVehiculo, ID)){
                JOptionPane.showMessageDialog(null, "Solicitud Aprobada exitosamente",
                        "mensaje", 1);
            
            }else{
                JOptionPane.showMessageDialog(null, "La solicitud No pudo ser aprobada",
                        "Alerta", 0);
            }
        
        }
    }//GEN-LAST:event_btnAprobarViajeActionPerformed

    private void btnRegistrarSecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarSecretariaActionPerformed
        if(ValidarSecretaria()){
            try{
                Secretaria nuevaSecretaria= new Secretaria();
                nuevaSecretaria.setNombreCompleto(jtfSectretariaNombre.getText());
                nuevaSecretaria.setCorreoElectronico(jtfSectretariaCorreo.getText());
                nuevaSecretaria.setNombreUsuario(jtfSectretariaCorreo.getText());
                nuevaSecretaria.setTelefono(Integer.parseInt(jtfSectretariaTelefono.getText()));
                nuevaSecretaria.setDepartamento(jtfSectretariaDepartamento.getText());
                
                if(usuario.AgregarSecretariaNUeva(nuevaSecretaria)){
                    JOptionPane.showMessageDialog(null, "La Secretaria fue Agregada",
                        "mensaje", 1);
                    LimpiarSecretaria();
                    
                }else{
                    JOptionPane.showMessageDialog(null, "La Secretaria No pudo ser registrada",
                        "Alerta", 0);
                }
             
            }
            catch(NumberFormatException nfe){
                 JOptionPane.showMessageDialog(null, "El telefono Solo puede\n"
                        + "contener numeros",
                        "Alerta", 2);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Falta algun campo por rellenar",
                    "Alerta", 2);
        }
        
    }//GEN-LAST:event_btnRegistrarSecretariaActionPerformed

    private void btnViajesPorEscuelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViajesPorEscuelasActionPerformed
       
        List<datoGrafico> infoDatos = usuario.infoGraficoCircular();
        Grafico temp = new Grafico();
        System.out.println(infoDatos.size());
        temp.GenerarGrafico(infoDatos);
        
    }//GEN-LAST:event_btnViajesPorEscuelasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAdministrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAdministrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAdministrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAdministrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAdministrados().setVisible(true);
            }
        });
    }

    /*----------Metodos de validacion de datos----------*/
    public boolean ValidarVehiculo() {
        if (jtfVehiculoPlaca.getText().equals("")
                || jtfVehiculoAnioFabricacion.getText().equals("")
                || jtfVehiculoColor.getText().equals("")
                || jtfVehiculoMarca.getText().equals("")
                || jtfVehiculoCapacidad.getText().equals("")
                || jtfVehiculoKilometraje.getText().equals("")
                || jtfVehiculoVIN.getText().equals("")
                || jtfVehiculoSede.getText().equals("")) {
            return false;
        }
        return true;
    }
    
    public boolean ValidarLicencia() {
        if (jtfLicenciaNombre.getText().equals("")
                || jtfLicenciaFechaExpiracion.getText().equals("")
                || jtfLicenciaFechaEmicion.getText().equals("")
                || jtfLicenciaTipo.getText().equals("")) {
            return false;
        }
        return true;
    }

    public boolean ValidarChofer() {
        if (jtfChoferNombre.getText().equals("")
                || jtfChoferCedula.getText().equals("")
                || jtfChoferCorreo.getText().equals("")
                || jtfChoferTelefono.getText().equals("")
                || licenciasChofer.isEmpty()) {
            return false;
        }
        return true;
    }
    public boolean ValidarSecretaria() {
        if (jtfSectretariaNombre.getText().equals("")
                || jtfSectretariaCorreo.getText().equals("")
                || jtfSectretariaDepartamento.getText().equals("")
                || jtfSectretariaTelefono.getText().equals("")) {
            return false;
        }
        return true;
    }

    /*----------Metodos de carga----------*/
    public void CargadorVentana(Administrador entrada) {
        usuario = entrada;
        this.setTitle("Administrador");
        
        ImageIcon imagen = new ImageIcon("src/Multimedia/FondoSecretaria.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(900,
                400, Image.SCALE_DEFAULT));
        lblFondo7.setIcon(icono);
        lblFondo2.setIcon(icono);
        lblFondo3.setIcon(icono);
        lblFondo1.setIcon(icono);
        lblFondo4.setIcon(icono);
        lblFondo5.setIcon(icono);
        lblFondo6.setIcon(icono);
        
        CargadorComboChofer();
        CargadorAprobar();
        
    }
    
    public void CargadorComboChofer() {
        jcbChoferLicencias.removeAllItems();
        lblCantLicencias.setText("Cant Licencias: " + licenciasChofer.size());
        for (Licencia temp : licenciasChofer) {
            jcbChoferLicencias.addItem(temp.getTipo());
        }
        
    }
    
    public void CargadorAprobar() {
        jcbAprobarChofer.removeAllItems();
        jcbAprobarVehiculo.removeAllItems();
        
        for (Chofer temp : main.miControlador.getMiTec().getChoferes()) {
            jcbAprobarChofer.addItem(temp.getNombreCompleto());
        }
        
        for (Vehiculo temp : main.miControlador.getMiTec().getVehiculos()) {
            jcbAprobarVehiculo.addItem("Placa: "+temp.getPlaca());
        }
        
    }

    /*----------Metodos de limpiesa UI----------*/
    public void LimpiarVehiculo() {
        jtfVehiculoPlaca.setText("");
        jtfVehiculoAnioFabricacion.setText("");
        jtfVehiculoColor.setText("");
        jtfVehiculoMarca.setText("");
        jtfVehiculoCapacidad.setText("");
        jtfVehiculoKilometraje.setText("");
        jtfVehiculoVIN.setText("");
        jtfVehiculoSede.setText("");
    }
    
    public void LimpiarLicencia() {
        jtfLicenciaNombre.setText("");
        jtfLicenciaFechaEmicion.setText("");
        jtfLicenciaFechaExpiracion.setText("");
        jtfLicenciaTipo.setText("");
        
    }
    
    public void LimpiarChofer(){
        jtfChoferCedula.setText("");
        jtfChoferCorreo.setText("");
        jtfChoferCedula.setText("");
        jtfChoferTelefono.setText("");
        licenciasChofer= new ArrayList();
        CargadorComboChofer();
    }
    public void LimpiarSecretaria(){
        jtfSectretariaNombre.setText("");
        jtfSectretariaCorreo.setText("");
        jtfSectretariaDepartamento.setText("");
        jtfSectretariaTelefono.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLicencia;
    private javax.swing.JButton btnAgregarVehiculo;
    private javax.swing.JButton btnAprobarViaje;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnAtras1;
    private javax.swing.JButton btnAtras2;
    private javax.swing.JButton btnAtras3;
    private javax.swing.JButton btnAtras4;
    private javax.swing.JButton btnAtras5;
    private javax.swing.JButton btnChoferAgregar;
    private javax.swing.JButton btnChoferQuitarLicencia;
    private javax.swing.JButton btnListarViajes;
    private javax.swing.JButton btnRegistrarSecretaria;
    private javax.swing.JButton btnViajesPorEscuelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcbAprobarChofer;
    private javax.swing.JComboBox<String> jcbAprobarVehiculo;
    private javax.swing.JComboBox<String> jcbChoferLicencias;
    private javax.swing.JPanel jpRegisChofer;
    private javax.swing.JTextArea jtaListarViajes;
    private javax.swing.JTextField jtfAprobarID;
    private javax.swing.JTextField jtfChoferCedula;
    private javax.swing.JTextField jtfChoferCorreo;
    private javax.swing.JTextField jtfChoferNombre;
    private javax.swing.JTextField jtfChoferTelefono;
    private javax.swing.JTextField jtfLicenciaFechaEmicion;
    private javax.swing.JTextField jtfLicenciaFechaExpiracion;
    private javax.swing.JTextField jtfLicenciaNombre;
    private javax.swing.JTextField jtfLicenciaTipo;
    private javax.swing.JTextField jtfSectretariaCorreo;
    private javax.swing.JTextField jtfSectretariaDepartamento;
    private javax.swing.JTextField jtfSectretariaNombre;
    private javax.swing.JTextField jtfSectretariaTelefono;
    private javax.swing.JTextField jtfVehiculoAnioFabricacion;
    private javax.swing.JTextField jtfVehiculoCapacidad;
    private javax.swing.JTextField jtfVehiculoColor;
    private javax.swing.JTextField jtfVehiculoKilometraje;
    private javax.swing.JTextField jtfVehiculoMarca;
    private javax.swing.JTextField jtfVehiculoPlaca;
    private javax.swing.JTextField jtfVehiculoSede;
    private javax.swing.JTextField jtfVehiculoVIN;
    private javax.swing.JLabel lblCantLicencias;
    private javax.swing.JLabel lblFondo1;
    private javax.swing.JLabel lblFondo2;
    private javax.swing.JLabel lblFondo3;
    private javax.swing.JLabel lblFondo4;
    private javax.swing.JLabel lblFondo5;
    private javax.swing.JLabel lblFondo6;
    private javax.swing.JLabel lblFondo7;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JLabel lblVehiculo1;
    // End of variables declaration//GEN-END:variables
}
