/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import aplicacion.Pasajero;
import aplicacion.Secretaria;
import aplicacion.Viaje;
import aplicacion.implementacion;
import java.awt.Image;
import java.text.*;
import javax.swing.*;
import java.util.*;

/**
 *
 * @author SSDesth
 */
public class frmSecretaria extends javax.swing.JFrame {

    private Secretaria usuarioActual;
    private List<Pasajero> listaPasajerosViaje = new ArrayList();

    /**
     * Creates new form frmSecretaria
     */
    public frmSecretaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpRegistrarPasajero = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfRegistrarNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfRegistrarCedula = new javax.swing.JTextField();
        jtfRegistrarDireccion = new javax.swing.JTextField();
        jtfRegistrarCorreo = new javax.swing.JTextField();
        jtfRegistrarTelefono = new javax.swing.JTextField();
        btnRegistrarPasajero = new javax.swing.JButton();
        lblRegistrarMensaje = new javax.swing.JLabel();
        lblFondoRegistrar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblCantPasajeros = new javax.swing.JLabel();
        jtfSolicitarPunto = new javax.swing.JTextField();
        jtfSolicitarFechaInicio = new javax.swing.JTextField();
        jtfSolicitarFechaFinalizacion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcbPasajeros = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jcbSolicitarQuitarPasajeros = new javax.swing.JComboBox<>();
        btnSolicitarAgregarPasajero = new javax.swing.JButton();
        btnSolicitarQuitarPasajero = new javax.swing.JButton();
        btnSolicitarViaje = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 600));

        jpRegistrarPasajero.setBackground(new java.awt.Color(0, 0, 255));
        jpRegistrarPasajero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        jpRegistrarPasajero.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));
        jpRegistrarPasajero.add(jtfRegistrarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 150, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cedula:");
        jpRegistrarPasajero.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Direccion:");
        jpRegistrarPasajero.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Correo:");
        jpRegistrarPasajero.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono:");
        jpRegistrarPasajero.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        jpRegistrarPasajero.add(jtfRegistrarCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 150, -1));
        jpRegistrarPasajero.add(jtfRegistrarDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 150, -1));
        jpRegistrarPasajero.add(jtfRegistrarCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 150, -1));
        jpRegistrarPasajero.add(jtfRegistrarTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 150, -1));

        btnRegistrarPasajero.setText("Registrar Pasajero");
        btnRegistrarPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPasajeroActionPerformed(evt);
            }
        });
        jpRegistrarPasajero.add(btnRegistrarPasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        lblRegistrarMensaje.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblRegistrarMensaje.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrarMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpRegistrarPasajero.add(lblRegistrarMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 290, 60));
        jpRegistrarPasajero.add(lblFondoRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -8, 710, 290));

        jTabbedPane1.addTab("Registrar Pasajero", jpRegistrarPasajero);

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Punto de Salida:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha Inicio:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha Finalizacion:");

        lblCantPasajeros.setForeground(new java.awt.Color(255, 255, 255));
        lblCantPasajeros.setText("Cant. Pasajeros: 0");

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Formato: dd-MM-aaaa");

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Formato: dd-MM-aaaa");

        jcbPasajeros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Agregar Pasajero:");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Quitar Pasajero:");

        jcbSolicitarQuitarPasajeros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSolicitarAgregarPasajero.setText("Agregar");
        btnSolicitarAgregarPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarAgregarPasajeroActionPerformed(evt);
            }
        });

        btnSolicitarQuitarPasajero.setText("Quitar");

        btnSolicitarViaje.setText("Solicitar Viaje");
        btnSolicitarViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarViajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfSolicitarFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfSolicitarFechaFinalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jtfSolicitarPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantPasajeros)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel12)
                                .addComponent(jcbPasajeros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSolicitarAgregarPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jcbSolicitarQuitarPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSolicitarQuitarPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnSolicitarViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfSolicitarPunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfSolicitarFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfSolicitarFechaFinalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCantPasajeros)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbSolicitarQuitarPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSolicitarAgregarPasajero)
                    .addComponent(btnSolicitarQuitarPasajero)
                    .addComponent(btnSolicitarViaje))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Solicitar Viaje", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Listar Solicitudes", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Consultar Solicitud", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cancelar Solicitud", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPasajeroActionPerformed
        try {
            if (ValidarCamposAgregarUsuario()) {
                Pasajero nuevoPasajero = new Pasajero();
                nuevoPasajero.setNombreCompleto(jtfRegistrarNombre.getText());
                nuevoPasajero.setCedula(Integer.parseInt(jtfRegistrarCedula.getText()));
                nuevoPasajero.setDireccion(jtfRegistrarDireccion.getText());
                nuevoPasajero.setCorreoElectronico(jtfRegistrarCorreo.getText());
                nuevoPasajero.setTelefono(Integer.parseInt(jtfRegistrarNombre.getText()));

                if (usuarioActual.RegistrarPasajero(nuevoPasajero)) {
                    JOptionPane.showMessageDialog(null, "Pasajero Registrado Exitosamente",
                            "Mensaje", 1);
                    CargadorPasajeros();
                    LimpiarCamposAgregarUsuario();
                    //Borrar Campos
                } else {
                    JOptionPane.showMessageDialog(null, "Pasajero No pudo ser Registrado",
                            "Alerta", 0);
                    //Borrar Campos
                }
            }

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "El campo de cedula o Telefono\n"
                    + "solo pueden tener numeros", "Alerta", 2);
        }


    }//GEN-LAST:event_btnRegistrarPasajeroActionPerformed

    private void btnSolicitarAgregarPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarAgregarPasajeroActionPerformed
        Pasajero temporal = implementacion.miControlador.getMiTec().
                getUsuarios().get(jcbPasajeros.getSelectedIndex());
        if (ValidadorSolicitarPasajero(temporal)) {
            listaPasajerosViaje.add(temporal);
            CargadorSolicitarPasajerosAgregados();
            JOptionPane.showMessageDialog(null, "El pasajero: " + temporal.getNombreCompleto()
                    + "\nCedula:" + temporal.getCedula()
                    + "\nse agrego Exitosamente a"
                    + "\nla lista de viaje", "Mensaje", 1);
        }

    }//GEN-LAST:event_btnSolicitarAgregarPasajeroActionPerformed

    private void btnSolicitarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarViajeActionPerformed
       
        if(ValidarCamposSolicitudViaje()){
            SimpleDateFormat traductor = new SimpleDateFormat("dd-MM-yyyy");
        Date fechaActrual = new Date();
        Date fechatemp;
        try {
            Viaje nuevoViaje = new Viaje();
            fechaActrual = traductor.parse(traductor.format(fechaActrual));

            nuevoViaje.setPuntoSalida(jtfSolicitarPunto.getText());
            fechatemp = traductor.parse(jtfSolicitarFechaInicio.getText());
            nuevoViaje.setFechaInicio(fechatemp);
            fechatemp = traductor.parse(jtfSolicitarFechaFinalizacion.getText());
            nuevoViaje.setFechaFinalizacion(fechatemp);

            nuevoViaje.setFechaSolicitud(fechaActrual);

            nuevoViaje.setPasajeros(listaPasajerosViaje);

            nuevoViaje.setConsecutivo("IVA-" + implementacion.miControlador.getMiTec().getViajes().size());

            if (usuarioActual.SolicitarViaje(nuevoViaje)) {
                JOptionPane.showMessageDialog(null, "Viaje Agregado");
                LimpiarCamposSolicitarViaje();
            } else {
                JOptionPane.showMessageDialog(null, "La solicitud de viaje\n"
                        + "fue Negada",
                         "Alerta", 0);
            }

        } catch (Exception e) {
            System.out.println(e.toString());
            JOptionPane.showMessageDialog(null, "Algun dato fue Agregado\n"
                    + "sin el formato Correcto",
                     "Alerta", 2);
        }
        }
        

    }//GEN-LAST:event_btnSolicitarViajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSecretaria().setVisible(true);
            }
        });
    }

    public void CargadorVentana(Secretaria entrada) {
        this.setTitle("Loggin");

        ImageIcon imagen = new ImageIcon("src/Multimedia/FondoSecretaria.png");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(700,
                400, Image.SCALE_DEFAULT));
        lblFondoRegistrar.setIcon(icono);

        usuarioActual = entrada;
        CargadorPasajeros();
        CargadorSolicitarPasajerosAgregados();
    }

    public void CargadorPasajeros() {
        List<Pasajero> temp = implementacion.miControlador.ObtenerListaUsuarios();
        jcbPasajeros.removeAllItems();
        for (Pasajero auxiliar : temp) {
            jcbPasajeros.addItem(auxiliar.getNombreCompleto());
        }

    }

    public void CargadorSolicitarPasajerosAgregados() {
        jcbSolicitarQuitarPasajeros.removeAllItems();
        for (Pasajero auxiliar : listaPasajerosViaje) {
            jcbSolicitarQuitarPasajeros.addItem(auxiliar.getNombreCompleto());
        }
        lblCantPasajeros.setText("Cant. Pasajeros: " + listaPasajerosViaje.size());
    }

    public boolean ValidadorSolicitarPasajero(Pasajero temporal) {
        for (Pasajero Auxiliar : listaPasajerosViaje) {
            if (Auxiliar.getCedula() == temporal.getCedula()) {
                JOptionPane.showMessageDialog(null, "No se puede Agregar\n"
                        + "al pasajero: " + temporal.getNombreCompleto()
                        + "\nCedula:" + temporal.getCedula()
                        + "\nYa que esta Agregado", "Alerta", 0);
                return false;
            }
        }
        return true;
    }

    /*---------Validar UI----------*/
    /**
     * Este metodo valida que todos los campos esten con informacion
     *
     * @return boolean
     */
    public boolean ValidarCamposAgregarUsuario() {
        if (jtfRegistrarNombre.getText().equals("")
                || jtfRegistrarCorreo.getText().equals("")
                || jtfRegistrarCedula.getText().equals("")
                || jtfRegistrarTelefono.getText().equals("")
                || jtfRegistrarDireccion.getText().equals("")) {
            return false;
        }
        return true;
    }

    /**
     * Este metodo valida que todos los campos esten con informacion
     *
     * @return boolean
     */
    public boolean ValidarCamposSolicitudViaje() {
        if (jtfSolicitarPunto.getText().equals("")) {
            return false;
        }
        return true;
    }

    /*---------Limpiar UI----------*/
    /**
     * Este metodo Limpia los campos de informacion
     */
    public void LimpiarCamposAgregarUsuario() {
        jtfRegistrarNombre.setText("");
        jtfRegistrarCorreo.setText("");
        jtfRegistrarCedula.setText("");
        jtfRegistrarTelefono.setText("");
        jtfRegistrarDireccion.setText("");
        
    }
    
    /**
     * Este metodo Limpia los campos de informacion
     */
    public void LimpiarCamposSolicitarViaje() {
       jtfSolicitarPunto.setText("");
       jtfSolicitarFechaInicio.setText("");
       jtfSolicitarFechaFinalizacion.setText("");
       listaPasajerosViaje= new ArrayList();
       CargadorSolicitarPasajerosAgregados();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarPasajero;
    private javax.swing.JButton btnSolicitarAgregarPasajero;
    private javax.swing.JButton btnSolicitarQuitarPasajero;
    private javax.swing.JButton btnSolicitarViaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcbPasajeros;
    private javax.swing.JComboBox<String> jcbSolicitarQuitarPasajeros;
    private javax.swing.JPanel jpRegistrarPasajero;
    private javax.swing.JTextField jtfRegistrarCedula;
    private javax.swing.JTextField jtfRegistrarCorreo;
    private javax.swing.JTextField jtfRegistrarDireccion;
    private javax.swing.JTextField jtfRegistrarNombre;
    private javax.swing.JTextField jtfRegistrarTelefono;
    private javax.swing.JTextField jtfSolicitarFechaFinalizacion;
    private javax.swing.JTextField jtfSolicitarFechaInicio;
    private javax.swing.JTextField jtfSolicitarPunto;
    private javax.swing.JLabel lblCantPasajeros;
    private javax.swing.JLabel lblFondoRegistrar;
    private javax.swing.JLabel lblRegistrarMensaje;
    // End of variables declaration//GEN-END:variables
}
